_target_: dawn.models.system2.ldm_support_prev.LatentMotionEstimation
pretrained: stable-diffusion-v1-5/stable-diffusion-v1-5
flow_to_rgb: False
use_cfg: False
use_interval: True
num_inference_steps: 25
input_type: rgb_static
support_types: ["rgb_gripper", ]
use_text_sentence: False
use_prev_flow: False
use_prev_img: False
# use_reconstruct_loss: True
# image_size: 256
# in_channels: 7
# out_channels: 2
# condition_dim: 512
# size: "B"