_target_: dawn.models.arch.LTM_latent.ImagineToAct
# _target_: dawn.models.system1.raft.RAFT

imagine_model: 
      _target_: dawn.models.system2.ldm.LatentMotionEstimation
      image_size: 256
      # in_channels: 7
      # out_channels: 2
      # condition_dim: 512
      # size: "B"
      flow_to_rgb: False
      use_cfg: False
      use_interval: True

action_model: 
      _target_: dawn.models.system1.tdp.TransformerDiffusionPolicy
      # image_size: 256
      in_channels: 5
      obs_dim: 768
      goal_dim: 768
      num_latents: 257

imagine_model_weights: ./outputs/DAWN_stage_1/2025-06-26_16-41-53/checkpoints/model_0050000.pth
# outputs/DAWN_stage_1/2025-06-25_13-52-47/checkpoints/model_0050000.pth
# /home/nero/Robotics/DAWN/outputs/checkpoints/model_0145000.pth
  
use_flow: True