_target_: dawn.models.arch.LTM_latent.ImagineToAct
# _target_: dawn.models.system1.raft.RAFT

imagine_model: 
      _target_: dawn.models.system2.ldm.LatentMotionEstimation
      image_size: 256
      flow_to_rgb: False

action_model: 
      _target_: dawn.models.system1.transformer.TransformerAction
      image_size: 256
      in_channels: 5
      action_space: 7
      num_actions: 10
      hidden_dim: 768
      num_layers: 6
      num_heads: 8
      mlp_dim: 2048

imagine_model_weights: /home/nero/Robotics/DAWN/outputs/DAWN_stage_1/2025-06-21_03-19-43/checkpoints/model_0050000.pth
# /home/nero/Robotics/DAWN/outputs/checkpoints/model_0145000.pth
  
use_flow: True