_target_: dawn.models.system1.langtomo.MotionEstimation
image_size: 128
in_channels: 7
out_channels: 2
condition_dim: 512
size: "B"
flow_to_rgb: False
pretrained: /home/nero/Robotics/DAWN/weights/LTM_sys2_oxe/oxe_002/diffusion_pytorch_model.safetensors
