_target_: dawn.models.arch.LTM_fake_TDP.ImagineToAct
# _target_: dawn.models.system1.raft.RAFT

imagine_model: 
      _target_: dawn.models.system1.raft.RAFT

action_model: 
      _target_: dawn.models.system2.vit.ViTAction
      image_size: 128
      patch_size: 16
      in_channels: 3
      action_space: 7
      num_actions: 10

      hidden_dim: 192
      num_layers: 12
      num_heads: 3
      mlp_dim: 798
    
  

