train:  
  _target_: dawn.data.calvin.calvin.CalvinDataset
  data_path: data/calvin/dataset_opt/calvin_debug_dataset
  split: training 

val:
  _target_: dawn.data.calvin.calvin.CalvinDataset
  data_path: data/calvin/dataset_opt/calvin_debug_dataset
  split: validation
