train:  
  _target_: dawn.data.calvin.calvin_video.CalvinVideoDataset
  data_path: data/calvin/dataset_opt_local/task_ABC_D
  split: training 
  num_frames: 5

val:
  _target_: dawn.data.calvin.calvin_video.CalvinVideoDataset
  data_path: data/calvin/dataset_opt_local/task_ABC_D
  split: validation 
  num_frames: 5
