train:  
  _target_: dawn.data.calvin.calvin.CalvinDataset
  data_path: data/realsense
  split: training 
  num_frames: 3

val:
  _target_: dawn.data.calvin.calvin.CalvinDataset
  data_path: data/realsense
  split: validation
  num_frames: 3
