train:  
  _target_: dawn.data.realworld.realworld.RealworldDataset
  data_path: data/realsense
  split: training 
  num_frames: 2

val:
  _target_: dawn.data.realworld.realworld.RealworldDataset
  data_path: data/realsense
  split: validation
  num_frames: 2
