defaults:
  - _self_
  - dataset: calvin_ABC_D
  - model: LDM_stage1

weights: null

project: DAWN

debug: false

accelerator:
  gradient_accumulation_steps: ${trainer.accumulate}
  mixed_precision: fp16
  log_with: wandb
  project_dir: ${trainer.save_dir}

loader:
  train_batch_size: 16
  val_batch_size: 16
  num_workers: 4

trainer:
  accumulate: 1
  total_steps: 50000
  log_interval: 20
  save_interval: 1000
  val_interval: 500
  save_dir: './outputs/${project}/${now:%Y-%m-%d_%H-%M-%S}'
  resume: false
  lr_warmup_steps: 100
  
optimizer:
  _target_: 'torch.optim.AdamW'
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]

seed: 0
