defaults:
  - _self_
  - model: LTM_VPP
  - task: calvin
  - annotation: validation
  
project: DAWN_infer

accelerator:
  mixed_precision: fp16
  log_with: wandb

seed: 0

weights: outputs/DAWN_stage_2/2025-06-23_01-54-07/checkpoints/model_0077000.pth
inference:
  save_dir: outputs/inference/${project}/${now:%Y-%m-%d_%H-%M-%S}
  num_sequences: 10
  dataset: data/calvin/datasets/task_ABC_D/validation
  ep_len: 360
  image_size: 256
debug: False