defaults:
  - _self_
  - model: LTM_VPP
  - task: calvin
  - annotation: validation
  
project: DAWN_infer

accelerator:
  mixed_precision: fp16
  log_with: wandb

seed: 0

weights: ./outputs/DAWN_stage_2/2025-08-30_12-27/checkpoints/model_0100000.pth
# ./outputs/DAWN_stage_2/2025-06-27_13-05-21/checkpoints/model_0002000.pth
# ./outputs/DAWN_stage_2/2025-06-27_13-05-21/checkpoints/model_0002000.pth
# ./outputs/DAWN_stage_2/2025-06-24_01-34-01/checkpoints/model_0100000.pth
# ./outputs/DAWN_stage_2/2025-06-28_01-39-28/checkpoints/model_0007000.pth
# ./outputs/DAWN_stage_2/2025-06-27_13-05-21/checkpoints/model_0002000.pth
# ./outputs_bigcornea/DAWN_stage_2/2025-06-24_01-34-01/checkpoints/model_0100000.pth

save_dir: outputs
inference:
  save_dir: ${save_dir}/${project}/${now:%Y-%m-%d_%H-%M}
  num_sequences: 1000
  seq_len: 5
  multistep: 10
  dataset: data/calvin/dataset/task_ABC_D/validation
  ep_len: 360
  image_size: 256
  record_rollout_videos: True
  record_flow: True
debug: False
