defaults:
  - basic_config
  - _self_
  - override dataset: calvin_ABC_D
  - override model: LDM_support

project: DAWN_stage_1

debug: false

loader:
  train_batch_size: 16
  num_workers: 4

trainer:
  total_steps: 100000
  
