defaults:
  - basic_config
  - _self_
  - override dataset: calvin_ABC_D
  - override model: LTM_state_dino

project: DAWN_stage_2
desc: "LTM VPP"
loader:
  train_batch_size: 16
  val_batch_size: 16

trainer:
  total_steps: 100000
  lr_warmup_steps: 10

# weights: ./outputs/DAWN_stage_2/2025-06-27_13-05-21/checkpoints/model_0002000.pth
# ./outputs/DAWN_stage_2/2025-06-27_09-07-05/checkpoints/model_0010000.pth

optimizer:
  _target_: 'torch.optim.AdamW'
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
