defaults:
  - basic_config
  - _self_
  - override dataset: calvin_ABC_D
  - override model: LTM_VPP

project: DAWN_stage_2

loader:
  train_batch_size: 64
  val_batch_size: 16

trainer:
  total_steps: 100000
